import {
  RiAlertLine,
  RiArrowRightLine,
  RiBuildingLine,
  RiCheckLine,
  RiArrowLeftLine,
  RiArrowRightSLine,
  RiCommandLine,
  RiBankCardLine,
  RiFileLine,
  RiFileTextLine,
  RiQuestionLine,
  RiImageLine,
  RiComputerLine,
  RiDashboardLine,
  RiLoader4Line,
  RiLoginBoxLine,
  RiMoonLine,
  RiMoreFill,
  RiMore2Fill,
  RiPixLine,
  RiAddLine,
  RiSettingsLine,
  RiSunLine,
  RiDeleteBinLine,
  RiTwitterXLine,
  RiUserLine,
  RiUser3Line,
  RiEditLine,
  RiUserUnfollowLine,
  RiCloseLine,
  RiGithubLine,
  RiArrowUpLine,
  RiArrowDownLine,
  RiArrowUpDownLine,
  RiLockFill,
  RiLockUnlockFill,
  RiRefreshFill,
  RiDraggable,
  RiFilterLine,
} from "@remixicon/react";

export type Icon = React.ComponentType<{
  className?: string;
  size?: string | number;
  [key: string]: unknown;
}>;

export const Icons = {
  dashboard: RiDashboardLine,
  logo: RiCommandLine,
  login: RiLoginBoxLine,
  close: RiCloseLine,
  lock: RiLockFill,
  unlock: RiLockUnlockFill,
  refresh: RiRefreshFill,
  spinner: RiLoader4Line,
  chevronLeft: RiArrowLeftLine,
  chevronRight: RiArrowRightSLine,
  trash: RiDeleteBinLine,
  employee: RiUserUnfollowLine,
  post: RiFileTextLine,
  page: RiFileLine,
  userPen: RiEditLine,
  user2: RiUser3Line,
  media: RiImageLine,
  settings: RiSettingsLine,
  billing: RiBankCardLine,
  building: RiBuildingLine,
  ellipsis: RiMoreFill,
  ellipsisVertical: RiMore2Fill,
  add: RiAddLine,
  warning: RiAlertLine,
  user: RiUserLine,
  arrowRight: RiArrowRightLine,
  help: RiQuestionLine,
  pizza: RiPixLine,
  sun: RiSunLine,
  moon: RiMoonLine,
  laptop: RiComputerLine,
  github: RiGithubLine,
  twitter: RiTwitterXLine,
  check: RiCheckLine,
  arrowUp: RiArrowUpLine,
  arrowDown: RiArrowDownLine,
  arrowUpDown: RiArrowUpDownLine,
  draggable: RiDraggable,
  filter: RiFilterLine,
};
